In [117]:
### How they do it in the Readme file ###
import numpy as np
import h5py

def load_data(hdf5_path):
    with h5py.File(hdf5_path, 'r') as hf:
        x = hf.get('x')
        y = hf.get('y')
        video_id_list = hf.get('video_id_list')
        x = np.array(x)
        y = list(y)
        video_id_list = list(video_id_list)
        
    return x, y, video_id_list

def uint8_to_float32(x):
    return (np.float32(x) - 128.) / 128.
    
def bool_to_float32(y):
    return np.float32(y)

path = '../packed_features/' #just if they can be found in other folders
files = ['bal_train','eval'] #forget about the 'unbal_train'S
extension = '.h5'
data = {}
for f in files:
    
    data[f] = {}
    hdf5_path = path+f+extension
    print('\nReading data from: '+hdf5_path)
    
    (x, y, video_id_list) = load_data(hdf5_path)
    x = uint8_to_float32(x)		# shape: (N, 10, 128)
    y = bool_to_float32(y)		# shape: (N, 527)
    data[f]['x'] = np.array(x)
    data[f]['y'] = np.array(y)
    data[f]['video_id_list'] = np.array([str(v)[2:-1] for v in video_id_list], dtype='bytes')
    
    # print info
    print('x',x.shape)
    print('y',y.shape)
    print('video id',len(video_id_list))
    


Reading data from: ../packed_features/bal_train.h5
x (22160, 10, 128)
y (22160, 527)
video id 22160

Reading data from: ../packed_features/eval.h5
x (20371, 10, 128)
y (20371, 527)
video id 20371


In [118]:
# Let's have a look at some of the data
for d in data.keys():
    print('\n\n'+d+':')
    params = ['x','y','video_id_list']
    for p in params:
        print('\n'+p+':')
        if p == 'video_id_list':
            pass
            print(data[d][p][0])
        else:
            print(data[d][p])



bal_train:

x:
[[[-0.2578125 -0.046875   0.1484375 ... -0.984375   0.484375  -1.       ]
  [-0.0390625 -0.1484375  0.0703125 ... -0.0390625  0.09375    0.9375   ]
  [-0.59375    0.0546875  0.1875    ... -1.         0.9921875 -1.       ]
  ...
  [-0.1328125 -0.0546875 -0.1640625 ... -1.         0.9921875  0.9921875]
  [-0.40625   -0.2421875  0.3125    ... -0.6796875  0.9921875  0.9921875]
  [-0.484375   0.125     -0.171875  ... -0.2421875  0.65625   -1.       ]]

 [[-0.375      0.4140625  0.6875    ...  0.6171875 -0.0390625  0.8203125]
  [-0.578125   0.9921875  0.3671875 ...  0.9921875  0.6015625 -0.5703125]
  [-0.03125    0.203125   0.2890625 ... -0.46875    0.2890625 -1.       ]
  ...
  [-0.34375    0.21875    0.15625   ... -1.        -0.484375   0.3359375]
  [-0.390625  -0.1484375  0.1640625 ... -0.9609375  0.703125   0.9921875]
  [-0.4375    -0.03125    0.21875   ...  0.0625     0.4140625  0.8359375]]

 [[-0.1640625  0.171875  -0.3046875 ...  0.9921875  0.9921875 -0.6328125]
  [ 0

In [ ]:
v = data[list(data.keys())[1]][params[2]]
find_id = '9OqtuFGCCR8'#'Sb0169-lqLs'
#print(v.)
for i in v:
    if i == find_id:
        print(i,' == '+find_id)
        break

In [ ]:
import os
def get_dir_files(path, just_filename=True):
    files = []
    for (dirpath, dirnames, filenames) in os.walk(path):
        if just_filename:
            files.extend([file for file in filenames])
        else:
            direc = dirpath.split('/')[-1]
            files.extend([direc+'/'+file for file in filenames])
    print('get_dir_files\nFiles: ',files)
    return files

audioset_path = '../packed_features/'
audioset_files = get_dir_files(path=audioset_path, just_filename=True)
audioset_files = [f for f in audioset_files if (f.split('.')[-1] == 'h5') and (f.split('_')[0] != 'unbal')]
print(audioset_files)

In [ ]:
# Can't use this magic because 'x' is 3D and 'y' is 2D...
import pandas as pd
h = pd.DataFrame()
h['1']= [1,2,3]
h['2']= [4,5,6]
h['id']= ['a','b','c']
h.set_index('id',inplace=True)
print(h.head())

j = pd.DataFrame()
j['4']= [41,42,43]
j['3']= [34,35,36]
j['id']= ['a','b','d']
j.set_index('id',inplace=True)
print(j.head())

result = pd.merge(h, j, on='id', how='inner')
print(result.head())

In [ ]:
q = np.array([[11,12,13], [31,32,33]])
p = np.array([[21,22], [41,42]])
print(q)
print(p)
print(np.concatenate((q.T, p.T), axis=0))
print(np.concatenate((np.array([]),p), axis=None))
a = pd.DataFrame()
a['a'] = np.concatenate((q.T, p.T), axis=0)
print(a.head())

In [ ]:
def read_h5_files(path, files, print_info=False):
    #initialization of outputs
    data = {}
    pd_data = pd.DataFrame()
    x_pd = np.array([])
    y_pd = np.array([])
    id_pd = np.array([])

    for f in files:
        data[f] = {}
        hdf5_path = path+f
        print('\nReading data from: '+hdf5_path)
        
        (x, y, video_id_list) = load_data(hdf5_path)
        x = np.array(uint8_to_float32(x))     # shape: (N, 10, 128)
        y = np.array(bool_to_float32(y))      # shape: (N, 527)
        video_id_list = np.array([str(v)[2:-1] for v in video_id_list]) # take just the ID

        data[f]['x'] = x
        data[f]['y'] = y
        data[f]['id'] = video_id_list

        #pd_data['x']
        x_pd= np.concatenate((x_pd,x), axis=0)
        y_pd= np.concatenate((y_pd,y), axis=0)
        id_pd= np.concatenate((id_pd,id), axis=0)
        #pd_data['y'] = np.concatenate((pd_data['y'],y), axis=None)
        #pd_data['id'] = np.concatenate((pd_data['id'],video_id_list), axis=None)
        
        # print info
        if print_info:
            print('x',x.shape)
            print('y',y.shape)
            print('video id',len(video_id_list))
    
        print(x_pd.shape)
        print(y_pd.shape)
        print(id_pd.shape)
        
    """
    pd_data['x'] = x_pd
    pd_data['y'] = y_pd
    pd_data['id'] = id_pd
    pd_data.set_index('id',inplace=True)
    """
    return {'dict_data':data, 'pd_data':pd_data}
    
audioset_path = '../packed_features/'
audioset_files = get_dir_files(path=audioset_path, just_filename=True)
# Keep just the ones with extension .h5 and NOT unbalanced data!
audioset_files = [f for f in audioset_files if (f.split('.')[-1] == 'h5') and (f.split('_')[0] != 'unbal')]
print(audioset_files)
audioset_data = read_h5_files(path=audioset_path, files=audioset_files, print_info=True)
# because we want it in DataFrame and not as dict, see the function
audioset_data = audioset_data['pd_data']
audioset_data.head()

In [ ]:
audioset_data.shape

### Write H5DF

In [70]:
import numpy as np
import h5py

# Create the file and fill it
filename = 'mytestfile.hdf5'
f = h5py.File(filename, 'a') # read/create the file
filekeys = [k for k in f.keys()]

if len(filekeys)<1: # is an empty file, just created
    #need to generate the data and save to the file
    arr = np.arange(100)
    print('arr = ',arr)
    grp = f.create_group('grp')
    dset = grp.create_dataset("init", data=arr)
    
    # If array of strings -> need to encode in UTF-8
    d = np.array(['9OqtuFGCCR8','Sb0169-lqLs'], dtype='bytes')
    #d = [v.encode('utf-8') for v in d] #or this instead of "dtype='bytes'"
    dset = grp.create_dataset("id", data=d)
    

# Load the file
f = h5py.File(filename, 'a')
data = f.get('grp/init')
data = np.array(data)
print('\n\ndata = ',data)

ids = np.array(f.get('grp/id'))
print('\nid: ',ids)

arr =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


data =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

id:  [b'9OqtuFGCCR8' b'Sb0169-lqLs']


In [80]:
type(ids[0]) == np.bytes_

True

In [104]:
dataset = {'x': np.zeros((1,2,2)),
           'y': np.array([]),
           'id': np.array([], dtype='bytes'),
           'onset': np.array([]),
           'offset': np.array([]),
           'event_label': np.array([], dtype='bytes'),
           'filename': np.array([], dtype='bytes')}
print(dataset)
a = dataset['x']
b = np.array([[[1,2],[3,4]]])
dataset['x'] = np.concatenate((a, b))
print(dataset['x'])

{'x': array([[[0., 0.],
        [0., 0.]]]), 'y': array([], dtype=float64), 'id': array([], dtype='|S1'), 'onset': array([], dtype=float64), 'offset': array([], dtype=float64), 'event_label': array([], dtype='|S1'), 'filename': array([], dtype='|S1')}
[[[0. 0.]
  [0. 0.]]

 [[1. 2.]
  [3. 4.]]]


In [134]:
# Detect files with strongly labeled data and concatenate them in a dict

data = {'hola':{'filename': np.array(['0'],dtype='bytes'),
            'onset': np.float32([1,2]),
            'offset': np.float32([0]),
            'event_label': np.array(['0'],dtype='bytes'),
            'video_id': np.array(['0'],dtype='bytes')
          },
        'hola2':{'filename': np.array(['0'],dtype='bytes'),
            'onset': np.float32([3,4]),
            'offset': np.float32([0]),
            'event_label': np.array(['0'],dtype='bytes'),
            'video_id': np.array(['0'],dtype='bytes')
          },
        'adeu': {'1':1, '2':2}}

str_files = []
for f in data.keys():
    for col in data[f].keys():
        if col == 'onset': # this file has strongly labeled data
            str_files.extend([f])
            break
# initialization (needed to concatenate)
str_lab = {'filename': np.array(['0'],dtype='bytes'),
            'onset': np.float32([0]),
            'offset': np.float32([0]),
            'event_label': np.array(['0'],dtype='bytes'),
            'video_id': np.array(['0'],dtype='bytes')
          }
print(str_files)
for f in str_files:
    isFirst = False
    if len(str_lab['onset'])<2 and str_lab['onset']==0.0:
        isFirst = True
    print(str_lab['onset'])
    a = str_lab['onset']
    b = data[f]['onset']
    str_lab['onset'] = np.concatenate((a,b))
    print(str_lab['onset'])
    
    if isFirst: # delete the initial value
        str_lab['onset'] = str_lab['onset'][1:]
        print(str_lab['onset'])

['hola', 'hola2']
[0.]
[0. 1. 2.]
[1. 2.]
[1. 2.]
[1. 2. 3. 4.]
