In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
#notebook
from IPython.display import display
pd.options.display.max_columns = None
pd.options.display.max_rows = None
import os

#### Get all files of this path
path = '../dcase2018_baseline/task4/dataset/metadata/'

def get_dir_files(path):
    files = []
    for (dirpath, dirnames, filenames) in os.walk(path):
        direc = dirpath.split('/')[-1]
        files.extend([direc+'/'+file for file in filenames])
    print('get_dir_files\nFiles: ',files)
    return files

files = get_dir_files(path)
#### For each file, print its: name, header and shape
#files = ['eval/eval.csv']

def read_files(path, files, print_info=False):
    data = {}
    for f in files:
        file_name = path+f
        meta_data = pd.read_csv(file_name,delimiter='\t',header=0)
        data[f] = meta_data
        if print_info:
            print('\n*************************\n'+f)
            print(meta_data.head())
            print(meta_data.shape)
    return data
        
data = read_files(path, files, True)
#print(data.keys())

get_dir_files
Files:  ['test/test.csv', 'test/files_to_remove.csv', 'train/unlabel_in_domain.csv', 'train/unlabel_out_of_domain.csv', 'train/weak.csv', 'eval/eval.csv']

*************************
test/test.csv
                           filename  onset  offset     event_label
0  Y00pbt6aJV8Y_350.000_360.000.wav   0.00   9.971  Vacuum_cleaner
1    Y00pK0GMmE9s_70.000_80.000.wav   0.00  10.000  Vacuum_cleaner
2    Y02sD1KJeoGA_50.000_60.000.wav   0.00  10.000          Frying
3    Y0bjUq9XMMmQ_30.000_40.000.wav   0.00  10.000          Frying
4    Y0cH_NlhhMAs_30.000_40.000.wav   1.71   6.005             Cat
(923, 4)

*************************
test/files_to_remove.csv
                         filename
0  Y0a8RB5eOGJ4_30.000_40.000.wav
1  Y0BnyrbZz8Jk_30.000_40.000.wav
2  Y0cGgIDhIfdA_30.000_40.000.wav
3  Y0CYxiRkfVhw_30.000_40.000.wav
4  Y0d8dFoWQ2KA_30.000_40.000.wav
(46, 1)

*************************
train/unlabel_in_domain.csv
                         filename
0  Y--CE2f-ttEQ_30.000_40.

In [3]:
# saving the video ID's in a np.array for each file
def get_video_ids(data):
    video_ids = {}
    for k in data.keys():
        # All YouTuBe video ID's consist of 11 characters, never consider the first 'Y'
        video_ids[k] = np.array([md[1:12] for md in data[k]['filename']])
    return video_ids

video_ids = get_video_ids(data)
#print(video_ids.keys())

# Check that it worked for the first 2 videos in the first file.
print('\n\nClip names:\n',data[list(data.keys())[0]]['filename'][:2])
print('\n\nClip ids:\n',list(video_ids.values())[0][:2])





Clip names:
 0    Y00pbt6aJV8Y_350.000_360.000.wav
1      Y00pK0GMmE9s_70.000_80.000.wav
Name: filename, dtype: object


Clip ids:
 ['00pbt6aJV8Y' '00pK0GMmE9s']


In [4]:
data2 = data['eval/eval.csv']
print(data2.keys())
print(data2.shape)
data2._set_item('hola', video_ids['eval/eval.csv'])
print(data2.head())

Index(['filename', 'onset', 'offset', 'event_label'], dtype='object')
(3186, 4)
                         filename  onset  offset         event_label  \
0    YSb0169-lqLs_0.000_9.000.wav  0.778   7.187                 Dog   
1  Y9OqtuFGCCR8_30.000_40.000.wav  0.000   0.302  Alarm_bell_ringing   
2  Y9OqtuFGCCR8_30.000_40.000.wav  0.789   1.126  Alarm_bell_ringing   
3  Y9OqtuFGCCR8_30.000_40.000.wav  1.567   1.939  Alarm_bell_ringing   
4  Y9OqtuFGCCR8_30.000_40.000.wav  2.368   2.728  Alarm_bell_ringing   

          hola  
0  Sb0169-lqLs  
1  9OqtuFGCCR8  
2  9OqtuFGCCR8  
3  9OqtuFGCCR8  
4  9OqtuFGCCR8  


In [5]:
data3 = pd.DataFrame()
print(data3)
data3.append(data2.iloc[0:10])

Empty DataFrame
Columns: []
Index: []


filename  onset  offset         event_label  \
0    YSb0169-lqLs_0.000_9.000.wav  0.778   7.187                 Dog   
1  Y9OqtuFGCCR8_30.000_40.000.wav  0.000   0.302  Alarm_bell_ringing   
2  Y9OqtuFGCCR8_30.000_40.000.wav  0.789   1.126  Alarm_bell_ringing   
3  Y9OqtuFGCCR8_30.000_40.000.wav  1.567   1.939  Alarm_bell_ringing   
4  Y9OqtuFGCCR8_30.000_40.000.wav  2.368   2.728  Alarm_bell_ringing   
5  Y9OqtuFGCCR8_30.000_40.000.wav  3.216   3.564  Alarm_bell_ringing   
6  Y9OqtuFGCCR8_30.000_40.000.wav  3.715   4.586  Alarm_bell_ringing   
7  Y9OqtuFGCCR8_30.000_40.000.wav  6.653   8.092  Alarm_bell_ringing   
8  Y9OqtuFGCCR8_30.000_40.000.wav  8.626  10.000  Alarm_bell_ringing   
9    YVWwk76SEAno_0.000_9.000.wav  1.544   2.194  Alarm_bell_ringing   

          hola  
0  Sb0169-lqLs  
1  9OqtuFGCCR8  
2  9OqtuFGCCR8  
3  9OqtuFGCCR8  
4  9OqtuFGCCR8  
5  9OqtuFGCCR8  
6  9OqtuFGCCR8  
7  9OqtuFGCCR8  
8  9OqtuFGCCR8  
9  VWwk76SEAno

In [51]:
dataset = {'x': np.zeros((1,3,2)),
    		   'y': np.array([]),
    		   'id': np.array([]),
    		   'onset': np.array([]),
    		   'offset': np.array([]),
    		   'event_label': np.array([]),
    		   'filename': np.array([])}
print(dataset['x'].shape)
dataset['x'] = np.concatenate((dataset['x'], np.array([[[1,2],[3,4],[5,6]]])))
print(dataset['x'].shape)
a = np.ones((10,3,2))
dataset['x'] = np.concatenate((dataset['x'], np.array([list(a)[0]])))
print(dataset['x'].shape)
index = 0
dataset['x'] = np.concatenate((dataset['x'], a[index:index+1]))
print(dataset['x'].shape)

print(dataset['x'])




(1, 3, 2)
(2, 3, 2)
(3, 3, 2)
(4, 3, 2)
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[1. 2.]
  [3. 4.]
  [5. 6.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [ ]:
ids = ['123','456','789']
if type(ids[0])==str:
    print(1)
else:
    print(0)